[firebase]
type="service_account"
project_id="healhubteam9"
private_key_id="758e2377b6de9d9909cfa62ed4b8d1cfb3a0fdca"
private_key="""-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCfxoaNK0Xgkadw
5RpHtpSRqktPZlSv8Rf8+ehDbm+YWh+DHPHFjxtaKPtUk62p54ySG7b8pB6qx4AQ
k+HieGGOdk4FxhxvBNdyQ/v8cSz4el3P/YyQOyu/Z1kyhIQxQ2Ue1ii/XHIXJ8fx
3u34T3nwQhBk9RXk4v4KCjkg08dWbC1DQfG/5fRl/HD/MSacReikK/5BOe7PVN9P
ke+/DHC3vruPVH4tRvAfao0Rywg+Wopsh0cqQA346pjJX58xAPwYyHWjowcVH1fZ
yQ4AYvv4prKrrlrd3bnrfQwnKKPCz7+dMr61IGphwC+KketwXS0UGt2QU5tf89U7
S0H+UvrZAgMBAAECggEAErPi+TBpEBYMsx7mWiGpt3lnMmaooCXJKJA6W3ZYcs2N
5cOkG3uaeI3Wibp1uC9GGa5L17wAaP5MY+RjqyZrSQlZLbzYhDhdXd9OZmj7GiT8
yUWFSDbc8p1O6CZx8PBSLG9mOqxAIKzD73Coi4oGHJUnJSI5S1803IkA0fJoYZm9
svzAFhIX2FGEylDcNT746EBuzR4kHw9zdmu/Lm9RK5KsogaGKytmA7JvxDW7UDJ8
pqUZsQlvi+cThp0kidTDrzMovyvmVrb2IkcFYxtqsMiOGTlbLjXJ44UcXw0rZa1H
ivr0d6c4X3Tic174EQZPSwUfqE+RL+vMlVxpe3NPgQKBgQDVD46v25JLLJQEG3qT
d8tSE3OygPBBDPxTYC/LQbUIo2qHZx1twKm/cpfjEZ7m2QfaiICaBu7oS30QJ6pA
hwrT8GLbiHDn7RqC3EtJB7KN7Fo9HHy0e46zghXL919CIZfknUv0mXdOcg8FDEnG
er6kJhf6HOT+lTK4WwJsJm2D+QKBgQC/+dI4+Kj1T7hxkR3jaT+8DKEI+byUzuQE
UpYQMcZGmJSZ+tOH5mnLNajJHRIzc5QqI2eOP8tUYnDW+o0afUTG1akYWgKrOWUP
ad9sCRBXwAGMAhsg0TuETrUGFWf1Zf8rMkYlkoTrD0S3OU7jIwYON1ymCP14fE0i
YHn+tbcl4QKBgBosfhfmfnNTt59FjOpe1hBwKU9tfZZQNRM9BsIOgWHdSXH23euk
tnW5ayVO/dlYIhnbmQjS/zh0RZnddZHVxSPCLTLQ8SXcv9wBmhIPqwS6W1+Uh1FY
uHAe8/SJoB8sp09Db5hN3hU599Rj7RA/9fmOYHWuZQdNZty0+Xg1xFBpAoGAL8VG
no6h3Ik96GSn/1LNXUn3OHiMiKsC6mBynw0DvcVyFO7pfEPFx59OpNzrDoqQL/wn
ZKpTOmhUk+o8+n55gtDgBwM+7sSVdURvKD8JJgzNVb2gaoYmPUIooZ7qA5Kh8GnO
MsNG+AcQnldQXgz1EMyN7XMHP9gOiaNgOBWXwYECgYBaUD46yvJGW7FJ+l+uSIYk
0Ovw3FZtZI8Hclz663wz9KDDG0PFcnjh8WgZTnmb+mp535ecCSzT5ieCXmGlwMeS
2uHm7VJaIg8yThYE/FxwcqE3HURBGCEwfiMc4GAizyJru8TMQ9E7USKn9Zjun9Vh
pwQ7M/3+UKbjxO/120OZYQ==
-----END PRIVATE KEY-----"""
client_email="firebase-adminsdk-fbsvc@healhubteam9.iam.gserviceaccount.com"
client_id="103496353972162522408"
auth_uri="https://accounts.google.com/o/oauth2/auth"
token_uri="https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url="https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url="https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40healhubteam9.iam.gserviceaccount.com"
universe_domain="googleapis.com"